spring.application.name=service-catalog
server.port=8083

# ── PostgreSQL ──────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:comunidade_db}
spring.datasource.username=${POSTGRES_USER:comunidade_user}
spring.datasource.password=${POSTGRES_PASSWORD:senha}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── RabbitMQ ────────────────────────────────────────────────────
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:comunidade_rabbit}
spring.rabbitmq.password=${RABBITMQ_PASS:senha}

# ── Redis ────────────────────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:senha}

# ── Keycloak (OAuth2 Resource Server) ────────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/comunidade
